"""userid

Revision ID: 95119dbdc091
Revises: df0a9663a291
Create Date: 2020-11-11 15:52:29.353496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95119dbdc091'
down_revision = 'df0a9663a291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('userId', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['userId'], ['id'])
    op.drop_column('transactions', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.drop_column('transactions', 'userId')
    # ### end Alembic commands ###
